# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  banner: <%= ENV["MYNA_BANNER"] %>
  client: <%= ENV["MYNA_CLIENT"] %>
  couch_encryption_key: <%= ENV["COUCH_ENCRYPTION_KEY"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: c152ed4542fa177796293e335fbf6f8052e5ae875f787d0fd1c4d3572b5d8375ff30b8d72cbb33b6e4b5281ec3ab6a2e33de3891e997bba97e9c535c3cd7c290

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  banner: <%= ENV["MYNA_BANNER"] %>
  client: <%= ENV["MYNA_CLIENT"] %>
  couch_encryption_key: <%= ENV["COUCH_ENCRYPTION_KEY"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
